const LOG_IN = "LOG_IN";
const GOOGLE_LOGIN = "GOOGLE_LOG_IN";
const TWO_FACTOR_AUTH_SUCCESS = "TWO_FACTOR_AUTH_SUCCESS"
const LOG_OUT = "LOG_OUT";
const AUTHENTICATE = "AUTHENTICATE";
const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";

export { LOG_IN, GOOGLE_LOGIN, TWO_FACTOR_AUTH_SUCCESS, LOG_OUT, AUTHENTICATE, UPDATE_USER_PROFILE };