const person = [
  {
    id: 1,
    name: "John Smith",
    email: "john@example.com",
    age: 30,
    image: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?cs=srgb&dl=pexels-simon-robben-614810.jpg&fm=jpg",
    userPosts: 6,
    followersCount: 1422,
    followingCount: 121,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    interests: ["Hiking", "Cooking", "Reading"],
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "jane@example.com",
    age: 25,
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cGVyc29ufGVufDB8fDB8fHww",
    userPosts: 6,
    followersCount: 752,
    followingCount: 225,
    address: {
      street: "456 Elm St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    interests: ["Painting", "Traveling", "Yoga"],
  },
  {
    id: 3,
    name: "George Washington",
    email: "george@example.com",
    age: 40,
    image: "https://images.pexels.com/photos/39866/entrepreneur-startup-start-up-man-39866.jpeg?cs=srgb&dl=pexels-pixabay-39866.jpg&fm=jpg",
    userPosts: 6,
    followersCount: 930,
    followingCount: 499,
    address: {
      street: "789 Oak St",
      city: "Chicago",
      state: "IL",
      zip: "60001",
    },
    interests: ["Gardening", "Music", "Photography"],
  },
  {
    id: 4,
    name: "Brenda Johnson",
    email: "brenda@example.com",
    age: 35,
    image: "https://www.shutterstock.com/shutterstock/photos/2262759289/display_1500/stock-photo-happy-business-colleagues-having-discussion-over-tablet-pc-2262759289.jpg",
    userPosts: 6,
    followersCount: 5204,
    followingCount: 324,
    address: {
      street: "101 Pine St",
      city: "San Francisco",
      state: "CA",
      zip: "94101",
    },
    interests: ["cooking", "running", "volunteering"],
  },
  {
    id: 5,
    name: "Michael Brown",
    email: "michael@example.com",
    age: 28,
    image: "https://media.istockphoto.com/id/1296158947/photo/portrait-of-creative-trendy-black-african-male-designer-laughing.jpg?s=612x612&w=0&k=20&c=1Ws_LSzWjYvegGxHYQkkgVytdpDcnmK0upJyGOzEPcg=",
    userPosts: 6,
    followersCount: 3211,
    followingCount: 728,
    address: {
      street: "222 Maple St",
      city: "Boston",
      state: "MA",
      zip: "02101",
    },
    interests: ["Programming", "Gaming", "Movies"],
  }, 
  {
    id: 6,
    name: "Alice Green",
    email: "alice@example.com",
    age: 31,
    image: "https://img.freepik.com/free-photo/happiness-wellbeing-confidence-concept-cheerful-attractive-african-american-woman-curly-haircut-cross-arms-chest-self-assured-powerful-pose-smiling-determined-wear-yellow-sweater_176420-35063.jpg",
    userPosts: 20,
    followersCount: 2218,
    followingCount: 700,
    address: {
      street: "222 Maple St",
      city: "Boston",
      state: "MA",
      zip: "02101",
    },
    interests: ["Programming", "Gaming", "Movies"],
  },
];

module.exports = person;
